# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('insert_time', models.DateTimeField(auto_now=True)),
                ('task_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Complete'), (0, 'Incomplete')], default=0)),
                ('complete_by', models.DateTimeField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField()),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
